
import { Perfume } from './types';

export const PERFUME_DATABASE: Perfume[] = [
  {
    "id": 1,
    "name": "Octarine Sanctum Arcanum",
    "top_notes": ["Italian Bergamot", "Ginger", "Mint"],
    "middle_notes": ["Mediterrian Fig", "White Cedarwood", "Green Melon"],
    "base_notes": ["Coconut", "Sandalwood", "Tonka Bean", "Madagascar Vanilla"],
    "inspiration": "Jean Paul Gaultier Le Beau Paradise Garden",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/30hitwRiC4",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYUCMbXVjk-N3Q5s/",
    "scent_family": ["Fresh", "Green", "Tropical"]
  },
  {
    "id": 2,
    "name": "Octarine Black XZ",
    "top_notes": ["Pineapple", "Lemon", "Apple"],
    "middle_notes": ["Violet Leaf", "Iris", "Geranium", "Fruity"],
    "base_notes": ["Cedarwood", "Amber", "Patchouli"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/6VHb4cGZtJ",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYUcL6Ydt6-96gNU/",
    "scent_family": ["Fruity", "Fresh", "Woody"]
  },
  {
    "id": 3,
    "name": "Octarine Caventus",
    "top_notes": ["Bergamot", "Blackcurrant", "Apple", "Lemon", "Pink Pepper"],
    "middle_notes": ["Pineapple", "Patchouli", "Moroccan Jasmine"],
    "base_notes": ["Birch", "Musk", "Oakmoss", "Ambroxan", "Cedarwood"],
    "inspiration": "Creed Aventus",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/9zrTFDCxn5",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYyBddrukd-z5AqD/",
    "scent_family": ["Fresh", "Fruity", "Woody"]
  },
  {
    "id": 4,
    "name": "Octarine Daniel Blue",
    "top_notes": ["Bergamot", "Lime", "Lemon", "Mandarin Orange", "Green Apple"],
    "middle_notes": ["Marine", "Lavender", "Coriander", "Rose", "Muguet"],
    "base_notes": ["Musk", "Amber", "Vanilla", "Cashmeran"],
    "inspiration": "Alfred Dunhill Desire Blue",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/3LKZJ8BtuG",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYypE4DvmR-yrTEv/",
    "scent_family": ["Aquatic", "Fresh", "Citrus"]
  },
  {
    "id": 5,
    "name": "Octarine Still Jenni",
    "top_notes": ["Earl Grey Tea", "White Pepper", "Mandarin Orange", "Apple", "Rice"],
    "middle_notes": ["Jasmine", "Lily of the Valley", "Freesia", "Honeysuckle", "Orange Blossom", "Rose"],
    "base_notes": ["Pepper", "Musk", "Sandalwood", "Iris", "Amber"],
    "inspiration": "Jennifer Lopez Still",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/5L5dh9zSKq",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYf4BPpSpv-efqD7/",
    "scent_family": ["Tea", "Floral", "Fresh"]
  },
  {
    "id": 6,
    "name": "Octarine 21 VP Men",
    "top_notes": ["Bergamot", "Orange", "Pepper", "Ginger"],
    "middle_notes": ["Vodka", "Lavender", "Mint", "Spices"],
    "base_notes": ["Amber", "Leather", "Woody"],
    "inspiration": "Carolina Herrera 212 VIP Men",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/8pfVrytpVI",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYP9DbEqDD-sbc5s/",
    "scent_family": ["Spicy", "Fresh", "Amber"]
  },
  {
    "id": 7,
    "name": "Octarine Sagewood Sea Salty",
    "top_notes": ["Grapefruit"],
    "middle_notes": ["Sea Salt", "Sage", "Lily of the Valley"],
    "base_notes": ["Ambrette", "Seaweed", "Cyclamen"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/8KjFHBKXcX",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYPv85MPBA-z83xq/",
    "scent_family": ["Aquatic", "Fresh", "Herbal"]
  },
  {
    "id": 8,
    "name": "Octarine [LIMITED STOCK] 20ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/2VlSKXux7O",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY5dgPeqRG-KZwQL/",
    "scent_family": ["Collection"]
  },
  {
    "id": 9,
    "name": "Octarine Bundling 2 20ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4fpwugRklZ",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY5PrQQWaK-tAagc/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 10,
    "name": "Octarine Bundling 3 20ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/9KbmTQo0wB",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYaB8Dde3n-uXfm6/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 11,
    "name": "Octarine Bundling 4 20ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/6AekhZvrJI",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY5t8vqof9-J0HyN/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 12,
    "name": "Octarine Bundling 5 20ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/10weY9IJOl",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYaj6s76F6-tZ5Nj/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 13,
    "name": "Octarine Bundling 10 20ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/7Kqi5zKUna",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYmWPMqSFn-oWo0F/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 14,
    "name": "Octarine Bundling 2 50ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/AUnjrqG5YA",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYa5twuwHh-Rv09W/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 15,
    "name": "Octarine Bundling 3 50ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/10weYPPb7x",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYaW9TuoAG-ywid5/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 16,
    "name": "Octarine Bundling 4 50ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/2qOIjy0EDA",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYu26XTrdw-6khcL/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 17,
    "name": "Octarine Bundling 5 50ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4AtgKNrQHy",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYaKpFWaM2-fKyWF/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 18,
    "name": "Octarine [EXCLUSIVE] Bundling 2",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4fpwvMx7EZ",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYma5jX8nk-lJVUt/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 19,
    "name": "Octarine [EXCLUSIVE] Bundling 3",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/1BG4kxwZR7",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYm9s5ESbX-7pEs2/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 20,
    "name": "Realman Pure Spicy",
    "top_notes": ["Orange", "Blossom", "Lemon"],
    "middle_notes": ["Lavender", "Cardamom", "Nutmeg"],
    "base_notes": ["Teak", "Wood", "Vetiver"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/6fb1Mc0wRp",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY4Q1woUPB-rWDVZ/",
    "scent_family": ["Spicy", "Citrus", "Woody"]
  },
  {
    "id": 21,
    "name": "Realman Pure Cologne",
    "top_notes": ["Saffron", "Jasmine"],
    "middle_notes": ["Amber", "Wood", "Ambergris"],
    "base_notes": ["Fir", "Resin", "Cedar"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/3fxPnTpT73",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYVcefdt5R-g690X/",
    "scent_family": ["Amber", "Woody", "Floral"]
  },
  {
    "id": 22,
    "name": "Realman Bundling 2",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/8KjFMEkrHY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYqBPrrdh1-4E7hg/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 23,
    "name": "Realman Bundling 3",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/6KyAyeLSNv",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYquR2Ajch-uIsZM/",
    "scent_family": ["Bundle"]
  },
  {
    "id": 24,
    "name": "Aerostreet Green Savana",
    "top_notes": ["Lemongrass", "Bergamot"],
    "middle_notes": ["Lemongrass", "Bergamot", "Tea"],
    "base_notes": ["Lemongrass", "Bergamot", "Tea"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/5L5dnHe14N",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYbHx6BYxh-bq0eY/",
    "scent_family": ["Green", "Tea", "Fresh"]
  },
  {
    "id": 25,
    "name": "Aerostreet Beach Sand",
    "top_notes": ["Lemon", "Bergamot", "Neroli"],
    "middle_notes": ["Pink Pepper", "Sea Sand", "Thyme"],
    "base_notes": ["Rosemary", "Cloves"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/30hj17wnX0",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYgJTSpfjo-CPV8Q/",
    "scent_family": ["Aquatic", "Fresh", "Herbal"]
  },
  {
    "id": 26,
    "name": "Royal Fragrance Sunrise of Java",
    "top_notes": ["Watermelon", "Pink Pepper", "Bergamot"],
    "middle_notes": ["Pineapple", "Rose", "Tiare Flower"],
    "base_notes": ["Patchouli", "Musk", "Sandalwood"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4LDEU3gFm4",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoxQwaqgMHx-gccG9/",
    "scent_family": ["Fruity", "Floral", "Fresh"]
  },
  {
    "id": 27,
    "name": "Royal Fragrance Symphony of Yogyakarta",
    "top_notes": ["Bergamot", "Blackcurrant", "Mandarin Orange"],
    "middle_notes": ["Neroli", "Lily", "Ylang-Ylang"],
    "base_notes": ["Sandalwood", "Vanilla", "Musk"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/Lh5ivctyq",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoxCfAW4gYd-0f46P/",
    "scent_family": ["Citrus", "Floral", "Amber"]
  },
  {
    "id": 28,
    "name": "Royal Fragrance Breeze in California",
    "top_notes": ["Clary Sage", "Blackberry", "Neroli"],
    "middle_notes": ["Nagarmotha", "Tuberose", "Orange Blossom"],
    "base_notes": ["Musk", "White Wood", "Black Vanilla"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/7pn6fqL7Yw",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoxVk4C8KuJ-rWXcG/",
    "scent_family": ["Floral", "Fruity", "Musk"]
  },
  {
    "id": 29,
    "name": "Royal Fragrance Artic Bloom",
    "top_notes": ["Mint", "Sea", "Ice"],
    "middle_notes": ["Freesia", "Daisy", "Aloevera"],
    "base_notes": ["Vetiver", "Juniper"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/W0Vwr63t6",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoxqmwD1FPw-Jhohr/",
    "scent_family": ["Aquatic", "Fresh", "Floral"]
  },
  {
    "id": 30,
    "name": "Mykonos Miniature Collection 15ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/20pMwOcft0",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQfoYEPqH-8Z0wr/",
    "scent_family": ["Collection"]
  },
  {
    "id": 31,
    "name": "Mykonos Collection 50ml",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Collection"]
  },
  {
    "id": 32,
    "name": "Mykonos Pink Beach 50ml",
    "top_notes": ["Kiwi", "Rhubarb", "Pink Pepper"],
    "middle_notes": ["Jasmine", "Watermelon", "Cyclamen"],
    "base_notes": ["Powdery Notes", "Sandalwood", "Tonka Bean", "Cedar", "Musk", "Juniper Berries"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/14IZG0WEA",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fruity", "Floral", "Powdery"]
  },
  {
    "id": 33,
    "name": "Mykonos California Signature 50ml",
    "top_notes": ["Mandarin Orange", "Lemon"],
    "middle_notes": ["Lychee", "Rosemary", "Cardamom", "Lavender", "Geranium", "Aquatic Notes"],
    "base_notes": ["Tonka Bean", "Teak Wood", "Vetiver"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Citrus", "Aquatic", "Fresh"]
  },
  {
    "id": 34,
    "name": "Mykonos Sorrento 50ml",
    "top_notes": ["Fizzy Grapefruit", "Bergamot", "Mandarin Orange", "Magnolia", "Ginger"],
    "middle_notes": ["Fizzy Grapefruit", "Neroli", "Ginger", "Powdery Notes", "Water Notes"],
    "base_notes": ["Fizzy Grapefruit", "Amber", "Musk", "Cedar", "Patchouli", "Orris Root"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Citrus", "Fresh", "Floral"]
  },
  {
    "id": 35,
    "name": "Mykonos Paradise 50ml",
    "top_notes": ["Coconut", "Mandarin Orange", "Pear", "Pineapple"],
    "middle_notes": ["Frangipani", "Jasmine", "Lily"],
    "base_notes": ["Amber", "Vanilla", "Woody"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/60LViqiieW",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Tropical", "Gourmand", "Floral"]
  },
  {
    "id": 36,
    "name": "Mykonos California Club 50ml",
    "top_notes": ["Bergamot", "Lemon", "Violet Leaf"],
    "middle_notes": ["Rose", "Violet", "Iris"],
    "base_notes": ["Amberwood", "Ambrette", "Sandalwood"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/2g53klYKt4",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopXCSptV6h-kkJFB/",
    "scent_family": ["Floral", "Powdery", "Woody"]
  },
  {
    "id": 37,
    "name": "Mykonos Slow Living 50ml",
    "top_notes": ["Amalfi Lemon", "Lemon Blossom"],
    "middle_notes": ["Neroli", "Lavender"],
    "base_notes": ["Orcanox™", "Musk", "Cedarwood"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fresh", "Citrus", "Musk"]
  },
  {
    "id": 38,
    "name": "Mykonos Glitch 50ml",
    "top_notes": ["Sicilian Bergamot", "Apple", "Grapefruit", "Charred Pineapple"],
    "middle_notes": ["Lavender", "Artemisia", "Lily of the Valley", "Pink Pepper", "Vanilla", "Dried Jasmine"],
    "base_notes": ["Patchouli", "Vanilla", "Musk"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fruity", "Fresh", "Amber"]
  },
  {
    "id": 39,
    "name": "Mykonos California Blue 50ml",
    "top_notes": ["Lavender", "Pear", "Grapefruit", "Pink Salt"],
    "middle_notes": ["Rhubarb", "Water Blossoms", "Marine Notes"],
    "base_notes": ["Moss", "Softwood", "Caramel"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Aquatic", "Fresh", "Gourmand"]
  },
  {
    "id": 40,
    "name": "Mykonos Reflection 50ml",
    "top_notes": ["Grapefruit", "Ginger", "Bergamot"],
    "middle_notes": ["Marine Notes", "Cardamom", "Lily of the Valley"],
    "base_notes": ["Musk", "Patchouli", "Amber", "Ambroxan"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fresh", "Aquatic", "Amber"]
  },
  {
    "id": 41,
    "name": "Velixir Demeter",
    "top_notes": ["Mint", "Lemon", "Basil", "Thyme"],
    "middle_notes": ["Blackcurrant", "Lavender", "Jasmine", "Rosemary"],
    "base_notes": ["Musk", "Cedarwood"],
    "inspiration": "Xerjoff Torino 21",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/2qOTvOq8GA",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopxJjFaXap-OTk3b/",
    "scent_family": ["Fresh", "Green", "Citrus"]
  },
  {
    "id": 42,
    "name": "Velixir Discovery Set",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/6VHmIGmLax",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopxmU1bXYA-2TL9b/",
    "scent_family": ["Discovery Set"]
  },
  {
    "id": 43,
    "name": "HMNS Farhampton 100ml",
    "top_notes": ["Bergamot", "Ripe Fruit"],
    "middle_notes": ["Lavender", "Orange Blossom"],
    "base_notes": ["Labdanum", "Cedarwood", "Tonka Beans"],
    "inspiration": null,
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/AUntJCC2Jj",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4g62BA1rt-xXu4M/",
    "scent_family": ["Woody", "Amber", "Floral"]
  },
  {
    "id": 44,
    "name": "HMNS Alpha 100ml",
    "top_notes": ["Citrus", "Grass"],
    "middle_notes": ["Cedarwood"],
    "base_notes": ["Green Tea"],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/2B8lNxRzYT",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4gaKJYau8-Lsyrr/",
    "scent_family": ["Fresh", "Tea", "Green"]
  },
  {
    "id": 45,
    "name": "HMNS Philea 100ml",
    "top_notes": ["Bergamot", "Magnolia", "Coriander Seed"],
    "middle_notes": ["Jasmine", "Mimosa Absolute", "Orange Blossom"],
    "base_notes": ["Cashmeran", "Heliotrope", "Musk"],
    "inspiration": null,
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/50SwlFjz3n",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4gpyy9cbB-eVOtO/",
    "scent_family": ["Floral", "Powdery", "Musk"]
  },
  {
    "id": 46,
    "name": "HMNS SORE Eterna 100ml",
    "top_notes": ["Bergamot", "Orange", "Petit Grain"],
    "middle_notes": ["Ylang-Ylang", "Rose", "Peach"],
    "base_notes": ["Cedarwood", "Musk", "Sandalwood"],
    "inspiration": null,
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/1Vt4ay2KnY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4pdcFMsAy-ZqI4u/",
    "scent_family": ["Floral", "Woody", "Citrus"]
  },
  {
    "id": 47,
    "name": "HMNS Discovery Set",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": null,
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/1qVv0hHG7e",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4GvH8Q6Yy-aishn/",
    "scent_family": ["Discovery Set"]
  },
  {
    "id": 48,
    "name": "Octarine Jasmine",
    "top_notes": ["Jasmine"],
    "middle_notes": ["Green"],
    "base_notes": ["Musk"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/7VA8J77ZuS",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYuyF61kMx-lhUzQ/",
    "scent_family": ["Floral", "Green", "Musk"]
  },
  {
    "id": 49,
    "name": "Octarine Gamuci Bloom",
    "top_notes": ["Jasmine", "Cyclamen"],
    "middle_notes": ["Tuberose", "Rose", "Ylang-Ylang"],
    "base_notes": ["Ranggon Creeper", "Musk", "Sandalwood"],
    "inspiration": "Gucci Bloom",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/40aG8m5UCl",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYugLJs4hd-XSKY4/",
    "scent_family": ["Floral", "White Floral"]
  },
  {
    "id": 50,
    "name": "Octarine Scandalusy",
    "top_notes": ["Melon", "Raspberry"],
    "middle_notes": ["Peony", "White Floral"],
    "base_notes": ["Vanilla", "Praline", "Musk"],
    "inspiration": "Victoria's Secret Scandalous",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/2B8bxU5ydK",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYu3Rmhbu3-y11EW/",
    "scent_family": ["Fruity", "Floral", "Gourmand"]
  },
  {
    "id": 51,
    "name": "Octarine Blooming Banquet",
    "top_notes": ["Mandarin Orange"],
    "middle_notes": ["Pink Peony", "Damask Rose", "Apricot", "Peach"],
    "base_notes": ["White Musk"],
    "inspiration": "Miss Dior Blooming Bouquet",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/8pfVtwX10N",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYHUxB1S8Y-fwiQl/",
    "scent_family": ["Floral", "Fruity", "Fresh"]
  },
  {
    "id": 52,
    "name": "Octarine Orchid Malice",
    "top_notes": ["Fruity"],
    "middle_notes": ["Floral"],
    "base_notes": ["Vanilla", "Nutty"],
    "inspiration": "Zara Orchid",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4q9N8r1do0",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYHTJpDuNd-5fD9o/",
    "scent_family": ["Floral", "Fruity", "Gourmand"]
  },
  {
    "id": 53,
    "name": "Octarine Romance Wish",
    "top_notes": ["Melon", "Pear", "Cucumber", "Pineapple"],
    "middle_notes": ["Freesia", "Cyclamen", "Violet", "White Floral", "Geranium"],
    "base_notes": ["Musk", "Raspberry", "Peach"],
    "inspiration": "Victoria's Secret Romantic Wish",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/AUnjtOuqdX",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY9DAJrFWh-agdKY/",
    "scent_family": ["Fruity", "Floral", "Fresh"]
  },
  {
    "id": 54,
    "name": "Octarine Baby Cuddles",
    "top_notes": ["Powdery"],
    "middle_notes": ["Rose", "White Floral"],
    "base_notes": ["Musk", "Cedarwood"],
    "inspiration": null,
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4AtgLrlXV2",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY9Xwcom6o-SMUaQ/",
    "scent_family": ["Powdery", "Floral", "Musk"]
  },
  {
    "id": 55,
    "name": "Octarine Librero",
    "top_notes": ["Lavender", "Mandarin Orange", "Blackcurrant", "Petitgrain"],
    "middle_notes": ["Lavender", "Orange Blossom", "Jasmine"],
    "base_notes": ["Madagascar Vanilla", "Musk", "Cedarwood", "Ambergris"],
    "inspiration": "Yves Saint Laurent Libre",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/qdENt3K9Z",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoY9opcqsLr-s28dP/",
    "scent_family": ["Floral", "Amber", "Fresh"]
  },
  {
    "id": 56,
    "name": "Octarine Bombastic Shell",
    "top_notes": ["Pineapple", "Pear", "Blackcurrant", "Bergamot", "Freesia"],
    "middle_notes": ["Pink Peony", "Lily of the Valley", "Rose", "Violet Leaf", "Aquatic"],
    "base_notes": ["Musk", "Vanilla", "Amber"],
    "inspiration": "Victoria's Secret Bombshell",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/3qGpxYw75w",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYxDtd1TTm-5LCr8/",
    "scent_family": ["Fruity", "Floral", "Fresh"]
  },
  {
    "id": 57,
    "name": "Octarine Omnia Athys",
    "top_notes": ["Green", "Pink Grapefruit"],
    "middle_notes": ["Iris", "Bulgarian Rose"],
    "base_notes": ["Heliotrope", "Woody"],
    "inspiration": "Bvlgari Omnia Amethyste",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/1LZUz6hIp8",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYxseT5WoQ-IwOgn/",
    "scent_family": ["Floral", "Green", "Powdery"]
  },
  {
    "id": 58,
    "name": "Octarine Pinky Chiffony",
    "top_notes": ["Wild Berries", "Pear", "Dewy Violet"],
    "middle_notes": ["Tiare Flower", "Jasmine", "Water Lily", "Coconut"],
    "base_notes": ["Vanilla", "White Musk", "Sandalwood"],
    "inspiration": "Bath & Body Works Pink Chiffon",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/3qGpxsSRqT",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYQNFanVv7-PAwp1/",
    "scent_family": ["Fruity", "Floral", "Gourmand"]
  },
  {
    "id": 59,
    "name": "Octarine Kanagita",
    "top_notes": ["Gardenia", "Cyclamen"],
    "middle_notes": ["Jasmine", "Rose", "White Floral"],
    "base_notes": ["Musk", "Sandalwood"],
    "inspiration": "Nagita Slavina",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/2VlSKAI3KG",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYPR1htRXb-wXwZp/",
    "scent_family": ["Floral", "White Floral", "Musk"]
  },
  {
    "id": 60,
    "name": "Royal Fragrance Blossom in Kyoto",
    "top_notes": ["Jasmine", "Green Notes"],
    "middle_notes": ["Tuberose", "Cedar", "Lily of the Valley"],
    "base_notes": ["Rangoon Creeper", "Musk", "Vanilla"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/50SvI6oBfO",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHox48SwMc1V-2EAGk/",
    "scent_family": ["Floral", "Green", "White Floral"]
  },
  {
    "id": 61,
    "name": "Mykonos Baby Love 50ml",
    "top_notes": ["Violet", "Musk", "Rose"],
    "middle_notes": ["Violet", "Rose"],
    "base_notes": ["Violet", "Musk"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/1gCWZ9jcNF",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Powdery", "Floral", "Musk"]
  },
  {
    "id": 62,
    "name": "Mykonos Verve 50ml",
    "top_notes": ["Vanilla", "Pear", "Blackcurrant"],
    "middle_notes": ["Jasmine", "Iris", "Orange Blossom"],
    "base_notes": ["Praline", "Vanilla", "Tonka Bean", "Patchouli"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/8AQ0JCIAse",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand", "Floral", "Amber"]
  },
  {
    "id": 63,
    "name": "Mykonos When in Paris 50ml",
    "top_notes": ["Mandarin Orange", "Lychee", "Marigold"],
    "middle_notes": ["Wild Orchid", "Vanilla Orchid", "Magnolia"],
    "base_notes": ["Apricot", "Cashmere Musk", "Guaiac Wood"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/8AQ0JCIAse",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Floral", "Fruity", "Amber"]
  },
  {
    "id": 64,
    "name": "Mykonos Luminos 50ml",
    "top_notes": ["Apple", "Banana"],
    "middle_notes": ["White Florals", "Rose", "Tuberose", "Lily of the Valley", "Orange Blossom", "Vanilla"],
    "base_notes": ["Amber", "Edible Notes", "Solar Accord", "Amberwood", "Cashmere", "Ice Cream"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand", "Floral", "Amber"]
  },
  {
    "id": 65,
    "name": "Mykonos XoXo Rosy 50ml",
    "top_notes": ["Turkish Rose", "Pink Pepper", "Green"],
    "middle_notes": ["Turkish Rose", "Rose Petals", "Orange Jam", "Red Berries"],
    "base_notes": ["Amber", "Musk", "Rose"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Floral", "Rose", "Fruity"]
  },
  {
    "id": 66,
    "name": "Mykonos Enchanted 50ml",
    "top_notes": ["Mandarin Orange"],
    "middle_notes": ["Peony", "Rose", "Violet", "Peach"],
    "base_notes": ["Iris", "Musk"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/gJzNcoTr6",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Floral", "Powdery", "Fresh"]
  },
  {
    "id": 67,
    "name": "Mykonos Rouge 50ml",
    "top_notes": ["Green Pear", "Lemon Blossom"],
    "middle_notes": ["Lily of the Valley", "Ambrette", "Violet"],
    "base_notes": ["Orcanox™", "Musks"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/7KqtJyQwJt",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopVTMWLSaM-IoDSK/",
    "scent_family": ["Fresh", "Floral", "Musk"]
  },
  {
    "id": 68,
    "name": "Velixir Paladin",
    "top_notes": ["Vanilla"],
    "middle_notes": ["Lavender"],
    "base_notes": ["Vetiver"],
    "inspiration": "Valentino Uomo Born In Roma Intense",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/6KyM64fTmu",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopxG7fXhjw-qdWLn/",
    "scent_family": ["Amber", "Aromatic", "Woody"]
  },
  {
    "id": 69,
    "name": "Velixir Hera",
    "top_notes": ["Pear", "Citrus", "Mandarin Orange"],
    "middle_notes": ["Lavender", "Violet"],
    "base_notes": ["Musk", "Sandalwood", "Vanilla", "Patchouli"],
    "inspiration": "Parfums de Marly Palatine",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/5AmOi0rrxE",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQJCKYgBP-lgAK8/",
    "scent_family": ["Floral", "Fruity", "Amber"]
  },
  {
    "id": 70,
    "name": "HMNS Essence of The Sun 100ml",
    "top_notes": ["Bergamot", "Coriander Seeds", "Pink Pepper"],
    "middle_notes": ["Tropical Flower", "Indian Jasmine Sambac", "Turkish Rose", "Tiare Flower", "Solar"],
    "base_notes": ["Vanilla Absolute", "Tonka Beans", "Ambrette", "Cedarwood"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/50SwlfaidK",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4psLnBYpj-DThwN/",
    "scent_family": ["Floral", "Amber", "Solar"]
  },
  {
    "id": 71,
    "name": "HMNS Untitled Humans Aroma 01 100ml",
    "top_notes": ["Coriander", "Violet Leaves", "Ambrette"],
    "middle_notes": ["Figolide", "Velvet", "Rose Absolute"],
    "base_notes": ["Sandalwood", "Cypriol", "Vanilla Jungle"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/4VWgAompYZ",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4pwhbwqn2-WvWi9/",
    "scent_family": ["Woody", "Green", "Floral"]
  },
  {
    "id": 72,
    "name": "HMNS Untitled Humans Aroma 02 100ml",
    "top_notes": ["Star Anise", "Star Fruit", "Starfish", "Star", "Rose Absolute"],
    "middle_notes": ["Violet", "Orris"],
    "base_notes": ["Musk Milk", "Cashmere"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/8APyY2ArPF",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4GRnvRJ5B-WuRaN/",
    "scent_family": ["Powdery", "Floral", "Musk"]
  },
  {
    "id": 73,
    "name": "HMNS Unrosed 100ml",
    "top_notes": ["Palmarosa"],
    "middle_notes": ["Earthy"],
    "base_notes": ["Musk"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/5L5nAkMZBV",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4svrPgM9F-DliWx/",
    "scent_family": ["Fresh", "Green", "Musk"]
  },
  {
    "id": 74,
    "name": "Octarine Veroz",
    "top_notes": ["Mint", "Apple", "Lemon"],
    "middle_notes": ["Tonka Bean", "Ambroxan", "Geranium"],
    "base_notes": ["Madagascar Vanilla", "Virginian Cedar", "Atlas Cedar", "Vetiver", "Oakmoss"],
    "inspiration": "Versace Eros",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/1VsvBlOIKG",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYQXSMJwTm-EgfZr/",
    "scent_family": ["Fresh", "Amber", "Aromatic"]
  },
  {
    "id": 75,
    "name": "Octarine Boujee Fluff",
    "top_notes": ["Lemon", "Strawberry", "Apple", "Freesia"],
    "middle_notes": ["Coconut", "Marshmallow", "Orange Blossom"],
    "base_notes": ["Whipped Cream", "Vanilla", "Musk"],
    "inspiration": "Kayali Yum Boujee Marshmallow",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/9fEcutcUzH",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYQwSva451-G3epY/",
    "scent_family": ["Gourmand", "Fruity", "Musk"]
  },
  {
    "id": 76,
    "name": "Octarine Elixir One",
    "top_notes": ["Crisp Asian Pear", "Davana"],
    "middle_notes": ["Damask Rose", "Cedar", "Osmanthus"],
    "base_notes": ["Vanilla", "Tonka Bean", "Patchouli"],
    "inspiration": "Rabanne 1 Million",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/60LKYGwMPn",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYCjdagXoT-9EpMO/",
    "scent_family": ["Amber", "Fruity", "Woody"]
  },
  {
    "id": 77,
    "name": "Octarine Noctis Obscura",
    "top_notes": ["Lychee", "Bergamot", "Mint"],
    "middle_notes": ["Indonesian Rose", "Pear", "Pink Pepper"],
    "base_notes": ["Vanilla", "Haitian Vetiver", "White Musk"],
    "inspiration": "Parfums de Marly Delina",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/W0O0R1YzM",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYCvEo5na1-N2bFL/",
    "scent_family": ["Floral", "Fruity", "Fresh"]
  },
  {
    "id": 78,
    "name": "Octarine Melon",
    "top_notes": ["Melon"],
    "middle_notes": ["Banana", "Apple"],
    "base_notes": ["Vanilla", "Milk", "White Floral"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/8fM5f6zwMk",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYfNjndA6A-8BRLw/",
    "scent_family": ["Fruity", "Gourmand", "Fresh"]
  },
  {
    "id": 79,
    "name": "Octarine Phillton Passport",
    "top_notes": ["Peach", "Red Berries", "Mandarin Orange"],
    "middle_notes": ["Honeysuckle", "Jasmine", "Peony"],
    "base_notes": ["Amber", "Musk", "Patchouli", "Vanilla"],
    "inspiration": "Paris Hilton",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/3B1SLjP6Gf",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZS91NvENsbrWQ-LqlVf/",
    "scent_family": ["Fruity", "Floral", "Amber"]
  },
  {
    "id": 80,
    "name": "Aerostreet Vivid Red",
    "top_notes": ["Blood Orange", "Mandarin Orange", "Honey"],
    "middle_notes": ["Honey", "Jasmine", "Caramel", "Gardenia"],
    "base_notes": ["Caramel", "Patchouli", "Honey"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4AtgPR1rNJ",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYgyfbpPJh-1ajRe/",
    "scent_family": ["Gourmand", "Citrus", "Floral"]
  },
  {
    "id": 81,
    "name": "Aerostreet Blush Orange",
    "top_notes": ["Rose", "Freesia", "Vanilla"],
    "middle_notes": ["Freesia", "Vanilla", "Patchouli"],
    "base_notes": ["Freesia", "Patchouli", "Woody", "Ambroxan"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/6KyAzY7MOP",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYgss3xByL-1fj3a/",
    "scent_family": ["Floral", "Amber", "Woody"]
  },
  {
    "id": 82,
    "name": "Royal Fragrance Whisper of Borneo",
    "top_notes": ["Red Berries", "Lychee", "Blackcurrant"],
    "middle_notes": ["Jasmine Sambac", "Honeysuckle"],
    "base_notes": ["Sugar", "Vanilla", "Amber"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/806WqXzMX2",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoxxE4mdh1p-dQUdk/",
    "scent_family": ["Fruity", "Gourmand", "Amber"]
  },
  {
    "id": 83,
    "name": "Royal Fragrance Evening in Venice",
    "top_notes": ["Mandarin Orange", "Blackcurrant"],
    "middle_notes": ["Rose", "Jasmine", "Orange Blossom"],
    "base_notes": ["Patchouli", "Vanilla", "Musk"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/50SvIKZJu2",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHox4CUf3LRq-S0i3z/",
    "scent_family": ["Floral", "Fruity", "Amber"]
  },
  {
    "id": 84,
    "name": "Mykonos Coconut Dreams 50ml",
    "top_notes": ["Coconut", "Aloe Vera", "Lily of the Valley"],
    "middle_notes": ["Coconut Cream", "Vanilla", "Sweet Rice"],
    "base_notes": ["Vanilla", "Cashmere Wood"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Tropical", "Gourmand", "Fresh"]
  },
  {
    "id": 85,
    "name": "Mykonos Vanilla Clouds 50ml",
    "top_notes": ["Vanilla", "Heliotrope", "White Floral"],
    "middle_notes": ["Vanilla", "Marshmallow", "Iris"],
    "base_notes": ["Caramel", "White Musk", "Vanilla"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/AAB4hUZMFf",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand", "Powdery", "Musk"]
  },
  {
    "id": 86,
    "name": "Mykonos Berry Caramel Pancake 50ml",
    "top_notes": ["Mixed Berry Coulis", "Brown Sugar", "Lemon"],
    "middle_notes": ["Smoked Brown Sugar Caramel", "Butter Pancake"],
    "base_notes": ["Caramel", "Blackberry", "Cashmere Wood", "Tonka Bean"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand", "Fruity"]
  },
  {
    "id": 87,
    "name": "Mykonos Silent Whisper 50ml",
    "top_notes": ["Apple", "Honeydew", "Melon"],
    "middle_notes": ["Lily of the Valley", "Amber"],
    "base_notes": ["Vanilla", "Amber"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fruity", "Fresh", "Amber"]
  },
  {
    "id": 88,
    "name": "Mykonos Bonfire Vanilla 50ml",
    "top_notes": ["Cloves", "Nutmeg", "Pink Pepper", "Orange Zest", "Vanilla"],
    "middle_notes": ["Smoked Wood", "Pepper", "Guaiac Wood", "Burnt Brown Sugar"],
    "base_notes": ["Smoked Wood", "Vanilla", "Marshmallow", "Caramel"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/70E2vkIvUq",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Woody", "Spicy", "Gourmand"]
  },
  {
    "id": 89,
    "name": "Mykonos Matcha Latte 50ml",
    "top_notes": ["Matcha", "White Chocolate", "Jasmine", "Tonka Bean", "Vanilla", "Milk Powder"],
    "middle_notes": ["Matcha", "White Chocolate", "Jasmine", "Tonka Bean", "Vanilla", "Milk Powder"],
    "base_notes": ["Matcha", "White Chocolate", "Jasmine", "Tonka Bean", "Vanilla", "Milk Powder"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Tea", "Gourmand", "Fresh"]
  },
  {
    "id": 90,
    "name": "Mykonos Caramel Fudge Cookie 50ml",
    "top_notes": ["Cookie Dough", "Caramel", "Vanilla"],
    "middle_notes": ["Caramel", "Condensed Milk", "Sea Salt"],
    "base_notes": ["White Musk", "Vanilla", "Caramel", "Praline"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand"]
  },
  {
    "id": 91,
    "name": "Mykonos Pink Drops 50ml",
    "top_notes": ["Strawberry Preserve", "Almond", "Caramel"],
    "middle_notes": ["Milk", "Heliotrope"],
    "base_notes": ["Vanilla", "White Musk"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand", "Fruity", "Musk"]
  },
  {
    "id": 92,
    "name": "Mykonos Milk Drops 50ml",
    "top_notes": ["Floral Bouquet", "Milk"],
    "middle_notes": ["Milk", "Green Notes"],
    "base_notes": ["Tonka Bean", "White Musk", "White Wood"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/40aRMKwaIP",
    "tokopedia_url": "",
    "scent_family": ["Gourmand", "Powdery", "Fresh"]
  },
  {
    "id": 93,
    "name": "Mykonos Cafe Drops 50ml",
    "top_notes": ["Orchid", "Jasmine", "Coffee"],
    "middle_notes": ["Vanilla", "Caramel", "Tonka Bean", "Milk"],
    "base_notes": ["Amber", "Musk", "Wood", "Patchouli"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/3B1KMqOvzN",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopgJYN3yM5-Z1q8m/",
    "scent_family": ["Gourmand", "Amber", "Woody"]
  },
  {
    "id": 94,
    "name": "Mykonos Royal Ispahan 50ml",
    "top_notes": ["Bergamot", "Raspberry", "Lychee", "Cotton Flower"],
    "middle_notes": ["Violet", "Rose Milk", "Soft Wood"],
    "base_notes": ["Vanilla", "Guaiac Wood", "Amber"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Floral", "Fruity", "Amber"]
  },
  {
    "id": 95,
    "name": "Mykonos Monaco Royale 50ml",
    "top_notes": ["Pear", "Melon", "Green Notes"],
    "middle_notes": ["Soft Wood", "Cedarwood"],
    "base_notes": ["Moss", "Caramel", "Musk"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fresh", "Woody", "Gourmand"]
  },
  {
    "id": 96,
    "name": "Mykonos Hawaiian Crush 50ml",
    "top_notes": ["Lychee", "Red Fruits", "Black Tea"],
    "middle_notes": ["Rose", "Lily of the Valley", "Lychee", "Black Tea"],
    "base_notes": ["Amber", "Patchouli", "Musk", "Incense"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/1BGFzGq7hn",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopbtWufc6k-850BT/",
    "scent_family": ["Fruity", "Tea", "Amber"]
  },
  {
    "id": 97,
    "name": "Mykonos Senja 50ml",
    "top_notes": ["Coffee", "Almond"],
    "middle_notes": ["Patchouli", "Chocolate", "Milk"],
    "base_notes": ["Sandalwood", "Chocolate", "Vetiver", "Cistus"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Gourmand", "Woody", "Earth"]
  },
  {
    "id": 98,
    "name": "Mykonos Chai Crema Latte 50ml",
    "top_notes": ["Cinnamon", "Gingerbread", "Coffee", "Cardamom"],
    "middle_notes": ["Tea Leaves", "Caramel", "Milk", "Hazelnut"],
    "base_notes": ["Vanilla", "Tonka Bean", "Musk", "Milk"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/9pYEJEaCCI",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopbcF5WpJc-MuH5e/",
    "scent_family": ["Spicy", "Gourmand", "Tea"]
  },
  {
    "id": 99,
    "name": "Velixir Athena",
    "top_notes": ["Lychee", "Rhubarb", "Grapefruit"],
    "middle_notes": ["Bulgarian Rose", "Freesia", "Vanilla"],
    "base_notes": ["Orris Root", "Musk", "Akigalawood", "Vetiver"],
    "inspiration": "Parfums de Marly Delina",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/3VeIizihXq",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZS91NnPTwX6PD-ZlTCo/",
    "scent_family": ["Floral", "Fruity", "Fresh"]
  },
  {
    "id": 100,
    "name": "Velixir Galatea",
    "top_notes": ["Biscuit", "Caramel"],
    "middle_notes": ["Milk", "Honey", "White Sugar", "Tonka Bean"],
    "base_notes": ["White Musk", "Vanilla", "Praline", "Amber"],
    "inspiration": "Giardini Di Toscana Bianco Latte",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/8pfp4svAAN",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZS91NnvUc7EcX-zixe3/",
    "scent_family": ["Gourmand", "Amber"]
  },
  {
    "id": 101,
    "name": "HMNS ORGSM Melting Temptation 100ml",
    "top_notes": ["Pear", "Apple", "Caramel"],
    "middle_notes": ["Woody", "Cocoa"],
    "base_notes": ["Vanilla", "Amber", "Musk"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/9KbvvQt2AD",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4prLCWbnp-HpNHE/",
    "scent_family": ["Gourmand", "Fruity", "Woody"]
  },
  {
    "id": 102,
    "name": "HMNS Unpatched 100ml",
    "top_notes": ["Jasmine Sambac", "Vanilla Madagascar", "Chocolate"],
    "middle_notes": ["Caramel", "Akigaiawood", "Rose"],
    "base_notes": ["Tonka Beans Brazil", "Amber", "Musk"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/4AtpmGe1na",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4sRKyEFjC-7qS0n/",
    "scent_family": ["Gourmand", "Amber", "Woody"]
  },
  {
    "id": 103,
    "name": "HMNS Addict 100ml",
    "top_notes": ["Berries"],
    "middle_notes": ["Red Rose", "Coffee"],
    "base_notes": ["Patchouli", "Amber", "Tonka Beans"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/AUntKNhwDZ",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4Grdjm41T-ogF6C/",
    "scent_family": ["Fruity", "Amber", "Spicy"]
  },
  {
    "id": 104,
    "name": "HMNS ORGSM 100ml",
    "top_notes": ["Red Apple"],
    "middle_notes": ["Rose", "Jasmine", "Peony"],
    "base_notes": ["Vanilla Beans", "Amber"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/1Vt4byUqJS",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4GxpybGS3-7iaAe/",
    "scent_family": ["Floral", "Fruity", "Amber"]
  },
  {
    "id": 105,
    "name": "Octarine Elixir Homme",
    "top_notes": ["Cardamom", "Lavender", "Mint"],
    "middle_notes": ["Vanilla", "Sandalwood"],
    "base_notes": ["Benzoin", "Tonka Bean", "Amber", "Patchouli"],
    "inspiration": "Jean Paul Gaultier Le Male Elixir",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/W0O0IMjFw",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYCmLHAnws-QuEtt/",
    "scent_family": ["Amber", "Aromatic", "Spicy"]
  },
  {
    "id": 106,
    "name": "Octarine Savage Men",
    "top_notes": ["Calabrian Bergamot", "Black Pepper", "Pepper"],
    "middle_notes": ["Sichuan Pepper", "Pink Pepper", "Lavender", "Vetiver", "Patchouli", "Geranium", "Elemi"],
    "base_notes": ["Ambroxan", "Cedarwood", "Labdanum"],
    "inspiration": "Dior Sauvage",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/1gCLOjB15N",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYXMfYNW9w-3mL5S/",
    "scent_family": ["Fresh", "Spicy", "Aromatic"]
  },
  {
    "id": 107,
    "name": "Octarine 1 M Lucky",
    "top_notes": ["Plum", "Ozonic", "Grapefruit", "Bergamot", "Pineapple"],
    "middle_notes": ["Hazelnut", "Vanilla", "Cedar", "Cinnamon", "Cashmere Wood", "Orange Blossom", "White Floral"],
    "base_notes": ["Sandalwood", "Amberwood", "Patchouli", "Vetiver", "Oakmoss"],
    "inspiration": "Rabanne 1 Million Lucky",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/4q9NAj3jJ3",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYXVN1Tx5B-t83Na/",
    "scent_family": ["Fruity", "Woody", "Gourmand"]
  },
  {
    "id": 108,
    "name": "Realman Pure Oriental",
    "top_notes": ["Truffle", "Plum"],
    "middle_notes": ["Rum", "Ylang-Ylang", "Black Orchid"],
    "base_notes": ["Patchouli"],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/qdEQ7Qm3t",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYVaspmbdh-r4d2S/",
    "scent_family": ["Amber", "Fruity", "Earth"]
  },
  {
    "id": 109,
    "name": "Fogg Attar Roll On",
    "top_notes": [], "middle_notes": [], "base_notes": [],
    "inspiration": "",
    "price": "< Rp99K",
    "shopee_url": "https://s.shopee.co.id/AUnjwXCvrT",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoYb8vHpXN1-tt925/",
    "scent_family": ["Oriental"]
  },
  {
    "id": 110,
    "name": "Mykonos Inception 50ml",
    "top_notes": ["Bergamot", "Ginger", "Orange", "Lemon"],
    "middle_notes": ["Neroli", "Cinnamon", "Black Tea", "Biga Flower"],
    "base_notes": ["Guaiac", "Musk", "Cedarwood", "LorenoxTM"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fresh", "Tea", "Spicy"]
  },
  {
    "id": 111,
    "name": "Mykonos Stilettos 50ml",
    "top_notes": ["Blackberry", "Sour Cherry", "Mandarin Orange"],
    "middle_notes": ["Violet", "Jasmine"],
    "base_notes": ["Cashmere Wood", "Amber", "Patchouli", "Musk", "Vanilla"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/2VldaC90na",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fruity", "Floral", "Amber"]
  },
  {
    "id": 112,
    "name": "Mykonos Invade 50ml",
    "top_notes": ["Pink Pepper", "Lavender Absolute", "Juniper"],
    "middle_notes": ["Cashmeran", "Cinnamon Bark", "Caramel"],
    "base_notes": ["Amber", "Madagascar Vanilla", "Drywoods"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/30huBBA6A0",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHoppB1v5xhG-EFwxs/",
    "scent_family": ["Aromatic", "Amber", "Spicy"]
  },
  {
    "id": 113,
    "name": "Mykonos Aphrodite 50ml",
    "top_notes": ["Jasmine", "Burnt Cinnamon", "Myrrh"],
    "middle_notes": ["Cedarwood", "Tonka Bean", "Sandalwood"],
    "base_notes": ["White Musk", "Tobacco", "Vanilla", "Mineral Amber"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/1Vt6OTZ5DT",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopp2hWbK7s-rXDtW/",
    "scent_family": ["Amber", "Spicy", "Woody"]
  },
  {
    "id": 114,
    "name": "Mykonos Down to Earth 50ml",
    "top_notes": ["Fig", "Matcha Green Tea", "Bergamot", "Incense", "Cinnamon"],
    "middle_notes": ["Cashmere Wood", "Orange", "Figolide", "Milky", "Orcanox"],
    "base_notes": ["Vetiver", "Sandalwood", "Santamanol", "Cedar"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Earth", "Green", "Woody"]
  },
  {
    "id": 115,
    "name": "Mykonos Dreamscape 50ml",
    "top_notes": ["Mango", "Italian Lemon", "Rhubarb"],
    "middle_notes": ["Ginger", "Jasmine", "Violet", "Praline", "Pink Pepper"],
    "base_notes": ["Cedar", "Grey Amber", "Tonka Beans", "Moss"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fruity", "Fresh", "Amber"]
  },
  {
    "id": 116,
    "name": "Mykonos Penthouse 50ml",
    "top_notes": ["Sparkling Blackcurrant", "Aldehydes", "Mandarin Zest", "Rose Mist"],
    "middle_notes": ["Velvety White Floral", "White Tea Vapor", "White Soap Accord", "Cashmere Wood", "Cedarwood"],
    "base_notes": ["Tonka Foam", "Iso E Super", "Amber", "Clean Musks", "Cashmeran"],
    "inspiration": "",
    "price": "Rp100K - Rp299K",
    "shopee_url": "https://s.shopee.co.id/4AtrXKfztY",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHopQ3vcfDjH-nEK63/",
    "scent_family": ["Fresh", "Floral", "Powdery"]
  },
  {
    "id": 117,
    "name": "HMNS Darker Shade of ORGSM 100ml",
    "top_notes": ["Orange Blossom", "Apple", "Pepper"],
    "middle_notes": ["Cypriol", "Caramel", "Patchouli"],
    "base_notes": ["Vanilla Beans", "Cedarwood", "Amber", "Vetiver"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/14Go8f04P",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4gw2WgEfp-jAHYA/",
    "scent_family": ["Amber", "Gourmand", "Spicy"]
  },
  {
    "id": 118,
    "name": "HMNS The Perfection 100ml",
    "top_notes": ["Bergamot", "Elemi", "Indonesian Clove", "Nutmeg"],
    "middle_notes": ["Lavender", "Tagetes", "Lily of the Valley", "Green Pear"],
    "base_notes": ["Driftwood", "Sandalwood", "Leather", "Musk"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/1Vt4b73Ixs",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4pfKtEcUb-xafe0/",
    "scent_family": ["Aromatic", "Woody", "Spicy"]
  },
  {
    "id": 119,
    "name": "HMNS The Prestige 100ml",
    "top_notes": ["Grapefruit", "Tobacco Leaves", "Pink Pepper", "Jungle"],
    "middle_notes": ["Patchouli", "Geranium", "Orris"],
    "base_notes": ["Toiu", "Vetiver", "Labdanum"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/70E19HdS2V",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4pXELTD6Y-o2lDi/",
    "scent_family": ["Amber", "Earth", "Spicy"]
  },
  {
    "id": 120,
    "name": "HMNS Ambar Janma 100ml",
    "top_notes": ["Bulgarian Rose", "Neroli", "Pink Pepper", "Lily of the Valley", "Black Tea"],
    "middle_notes": ["Sandalwood", "Amberwood", "Suede", "Gayo Patchouli"],
    "base_notes": ["Sandalwood", "Amberwood", "Suede", "Gayo Patchouli"],
    "inspiration": "",
    "price": "> Rp300K",
    "shopee_url": "https://s.shopee.co.id/3Ve8zaBN2Z",
    "tokopedia_url": "https://vt.tokopedia.com/t/ZSHo4GUwGn7eF-IIYFK/",
    "scent_family": ["Amber", "Woody", "Spicy"]
  }
];
